CREATE TABLE IF NOT EXISTS attacksBuffs (
    `ID` INT Primary Key,
    `Name` VARCHAR(34) CHARACTER SET utf8,
    `Damage` INT,
    `Effects_Buffs` INT,
    `Target_Self_Enemy` VARCHAR(5) CHARACTER SET utf8,
    `Composer` VARCHAR(24) CHARACTER SET utf8
);
INSERT INTO attacksBuffs VALUES
    (1,'Piano Concerto No. 21',15,0,'Enemy','Wolfgang Amadeus Mozart'),
    (2,'Requiem, K. 626: Lacrimosa',10,0,'Enemy','Wolfgang Amadeus Mozart'),
    (3,'Symphony No.25',5,0,'Enemy','Wolfgang Amadeus Mozart'),
    (4,'Piano Sonata No.16',0,10,'Self','Wolfgang Amadeus Mozart'),
    (5,'Sonata No. 14 ‘Moonlight’',15,0,'Enemy','Ludwig van Beethoven'),
    (6,'Bagatelle No. 25',10,0,'Enemy','Ludwig van Beethoven'),
    (7,'Symphony No. 5',5,0,'Enemy','Ludwig van Beethoven'),
    (8,'Für Elise',0,10,'Self','Ludwig van Beethoven'),
    (9,'Cello Suite No.1',15,0,'Enemy','Johann Sebastian Bach'),
    (10,'The Well-Tempered Clavier',10,0,'Enemy','Johann Sebastian Bach'),
    (11,'Goldberg Variations',5,0,'Enemy','Johann Sebastian Bach'),
    (12,'Unaccompanied Cello Suite No.1',0,10,'Self','Johann Sebastian Bach'),
    (13,'Wiegenlied',15,0,'Enemy','Johannes Brahms'),
    (14,'Sechs Klavierstücke',10,0,'Enemy','Johannes Brahms'),
    (15,'Hungarian Dance No.5',5,0,'Enemy','Johannes Brahms'),
    (16,'Symphony No. 3',0,10,'Self','Johannes Brahms'),
    (17,'Nocturne en mi bémol majeur opus 9',15,0,'Enemy','Frederic Chopin'),
    (18,'Nocturne No. 20',10,0,'Enemy','Frederic Chopin'),
    (19,'Nocturne No. 2',5,0,'Enemy','Frederic Chopin'),
    (20,'Nocturne, Op. posth.',0,10,'Self','Frederic Chopin'),
    (21,'Clair de Lune',15,0,'Enemy','Claude Debussy'),
    (22,'Suite bergamasque',10,0,'Enemy','Claude Debussy'),
    (23,'Rêverie',5,0,'Enemy','Claude Debussy'),
    (24,'Suite bergamasque, L. 75',0,10,'Self','Claude Debussy'),
    (25,'Cello Concerto No. 1',15,0,'Enemy','Franz Joseph Haydn'),
    (26,'String Quartet No. 62',10,0,'Enemy','Franz Joseph Haydn'),
    (27,'Symphony No. 104',5,0,'Enemy','Franz Joseph Haydn'),
    (28,'Piano Sonata (Partita)',0,10,'Self','Franz Joseph Haydn'),
    (29,'Devil’s Trill',15,0,'Enemy','Giuseppe Tartini'),
    (30,'Devil’s Trill III',10,0,'Enemy','Giuseppe Tartini'),
    (31,'Sonata in G Minor',5,0,'Enemy','Giuseppe Tartini'),
    (32,'Devil’s Trill I',0,10,'Self','Giuseppe Tartini'),
    (33,'Swan Lake',15,0,'Enemy','Pyotr Ilyich Tchaikovsky'),
    (34,'The Nutcracker',10,0,'Enemy','Pyotr Ilyich Tchaikovsky'),
    (35,'Variations on a Rococo Theme',5,0,'Enemy','Pyotr Ilyich Tchaikovsky'),
    (36,'Album for the Young',0,10,'Self','Pyotr Ilyich Tchaikovsky'),
    (37,'Doot Doot',15,0,'Enemy','Trumpet Boy'),
    (38,'Scales',10,0,'Enemy','Trumpet Boy'),
    (39,'Put pa da put',5,0,'Enemy','Trumpet Boy'),
    (40,'HONK',0,10,'Self','Trumpet Boy'),
    (41,'Vivaldi Variation',15,0,'Enemy','Antonio Vivaldi'),
    (42,'Violin Concerto in G Minor',10,0,'Enemy','Antonio Vivaldi'),
    (43,'The Four Seasons',5,0,'Enemy','Antonio Vivaldi'),
    (44,'The Four Seasons - Summer',0,10,'Self','Antonio Vivaldi'),
    (45,'Die Walkure',15,0,'Enemy','Richard Wagner'),
    (46,'Lohengrin',10,0,'Enemy','Richard Wagner'),
    (47,'Tannhäuser',5,0,'Enemy','Richard Wagner'),
    (48,'La Cabalgata De Las Valkirias',0,10,'Self','Richard Wagner');
