CREATE TABLE IF NOT EXISTS gameState (
    `gameID` VARCHAR(255) CHARACTER SET utf8,
    `Player1` VARCHAR(255) CHARACTER SET utf8,
    `P1_C1` TINYINT,
    `P1_C2` TINYINT,
    `P1_C3` TINYINT,
    `Player2` VARCHAR(255) CHARACTER SET utf8,
    `P2_C1` TINYINT,
    `P2_C2` TINYINT,
    `P2_C3` TINYINT
);